# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 807025d3136a9a32fa5e0e4e1660dcfb6245f5c5f309884e1bdfebbd4fcb771c1154f7a661761cbad79fd8f1c8aca4c8364b5ca56cfdbe084f438024272d22b4

test:
  secret_key_base: 97be1d2055330a9836a4b406582656666ee0b51c223935c7a0b460abcec47bc1f8beb786edaa70f124951a532a16aadf71c695b1751d3287a7adf00d1edb1bb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
